version: '3.1'

services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /home/Cassio/Docker/Volumes/MongoDB:/data/db
#    networks:
#      rede:
#        ipv4_address: 10.5.0.20

  gestao-notas:
    image: gestao-notas
    depends_on:
      - mongodb
    ports:
      - 8080:8080
#    networks:
#      rede:
#        ipv4_address: 10.5.0.10


networks:
  rede:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

