server:
  port: 8080

spring:
  profiles:
    active: dev

---

spring:
  profiles: prod
  data:
    mongodb:
      uri: 'mongodb+srv://admin:QWbXinIPMzl4tDWO@cluster1.sxrjt.mongodb.net/whatsapp-mern?retryWrites=true&w=majority'

---

spring:
  profiles: dev
  data:
    mongodb:
      database: banco
      host: localhost
      port: 27017